name: CI - Build and Tests

#
# Controla quando a Action será disparada. Neste caso é disparado quando ocorre um
# push ou pull request em qualquer branch.
#
on:
  push:
 #  branches: [ develop ]
  pull_request:
 #  branches: [ develop ]

jobs:
  #
  # Este workflow tem dois jobs, um para Build e outro para Teste
  #
  build-and-test:

    runs-on: ubuntu-latest

    #
    # Sequencia de execução das tarefas do job.
    #
    steps:
    #
    # Checkout o repositório para poder ter acesso a ele.
    #
    - uses: actions/checkout@v2
    #
    # Configura os pacotes nas versões necessárias
    #
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.401
    #
    # Instala todas as depedências do projeto.
    #
    - name: Install dependencies
      run: dotnet restore
    #
    # Faz o build do projeto.
    #
    - name: Build
      run: dotnet build --configuration Release --no-restore
    #
    # Executa todos os testes do projeto.
    #
    - name: Test
      run: dotnet test --no-restore --verbosity normal
